### ISSUE TITLE
Add to sindresorhus/awesome

### ISSUE THREAD

**Issue by eric-hc** [beansource/awesome-orgs#32]
Add `awesome-orgs` to  https://github.com/sindresorhus/awesome 

Per [requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-pull-request):
- [x] At least 30 days (initial commit https://github.com/beansource/awesome-orgs/commit/47095abd125698ac077639d6e9968bddd2c1bf0f)
- [x] You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).
  - https://github.com/sindresorhus/awesome/pull/2525#pullrequestreview-1327267017
  - https://github.com/sindresorhus/awesome/pull/2539#issuecomment-1464266843 
- [x] Run [awesome-lint](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues.
- [x] The default branch should be named [main, not master](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] Includes a succinct description of the project/theme at the top of the readme.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] The repo name of your list should be in lowercase slug format: awesome-name-of-list.
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: # Awesome Name of List.
- [x] The repo should have awesome-list & awesome as [GitHub topics](https://help.github.com/articles/about-topics).
- [x] Non-generated Markdown file in a GitHub repo.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [x] Includes a project logo/illustration whenever possible.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
  - Should be placed on the right side of the readme heading.
  - Can be placed centered if the list has a centered graphics header.
  - [x] Should link back to this list.
- [x] Has a Table of Contents section.
- [x] Has an appropriate license.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
- [x] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a Footnotes section at the bottom of the readme. The section should not be present in the Table of Contents.
- [x] Has consistent formatting and proper spelling/grammar.
- [x] Does not use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Does not include a CI (e.g. GitHub Actions) badge.
- [x] Does not include an Inspired by awesome-foo or Inspired by the Awesome project kinda link at the top of the readme. The Awesome badge is enough.

**Comment by swand0g** [comment]
https://github.com/sindresorhus/awesome/pull/2560

**Comment by Siimarras** [comment]
Rules are necessary

**Comment by swand0g** [comment]
:(

**Comment by eric-hc** [comment]
This request has been officially denied.
