### ISSUE TITLE
new org: pnpm

### ISSUE THREAD

**Issue by eric-hc** [beansource/awesome-orgs#42]
### Org name

pnpm

### Handle

pnpm

### Description

Fast, disk space efficient package manager -- 快速的，节省磁盘空间的包管理工具

### Org category

Web

### What makes this org awesome?

I can fill it in later.

### Org URL

https://github.com/pnpm

### Criteria

- [X] I attest!

### Code of conduct

- [X] I agree to follow `awesome-orgs`'s Code of Conduct

**Comment by swand0g** [comment]
is it awesome 🤔
