### ISSUE TITLE
new org: Poppinss

### ISSUE THREAD

**Issue by eric-hc** [beansource/awesome-orgs#47]
### Org name

Poppinss

### Handle

poppinss

### Description

Small focused modules for Node.js.

### Org category

Web

### What makes this org awesome?

Cool useful projects!

### Org URL

https://github.com/poppinss

### Criteria

- [X] I attest!

### Code of conduct

- [X] I agree to follow `awesome-orgs`'s Code of Conduct

**Comment by swand0g** [comment]
I LIKE IT
