### ISSUE TITLE
new org: axo

### ISSUE THREAD

**Issue by eric-hc** [beansource/awesome-orgs#53]
### Org name

Axo

### Handle

axodotdev

### Description

Collection of open source Rust libraries and tools.

### Org category

Other

### What makes this org awesome?

Pretty cool repos!

### Org URL

https://github.com/axodotdev

### Criteria

- [X] I attest!

### Code of conduct

- [X] I agree to follow `awesome-orgs`'s Code of Conduct

**Comment by swand0g** [comment]
COOL
